# Server
server.port=8080
# SQL Server Configuration
spring.datasource.url=jdbc:sqlserver://localhost\\SQLEXPRESS;databaseName=inventory_db;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Admin@1234
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# JWT
app.jwt.secret=SmartInventoryJWTSecretKeyHariKrishna2024SuperSecretKey
app.jwt.expiration=86400000

# Low Stock
app.inventory.low-stock-threshold=10

# Logging
logging.level.com.inventory=INFO  
spring.main.allow-circular-references=true
